### PR TITLE
deleted

### PR DESCRIPTION
**Pull request by mokeira**

### CODE REVIEW

**Comment by OtizAdoniz** [comment]
Yes, I'm back online. Let set the ball rolling. I am still familiarizing myself with GitHub
crude outline

**Comment by OtizAdoniz** [comment]
I am still writing the basic HTML homepage. What I want you to do is to make it responsive. In that a user can upload and retrieve data from it

**Comment by OtizAdoniz** [comment]
I usually use notepad to make webpages(a true programmer I am) so there might be errors which you can correct in case you notice them. I would like to use "FontAwesome" font but you can gimme your suggestions in case you do not like "FontAwesome"

**Comment by OtizAdoniz** [comment]
I also be using "Afrika..." font 
[fonts-of-afrika_afrika-t-ubuntu.zip](https://github.com/OtizAdoniz/project-transpacific/files/829972/fonts-of-afrika_afrika-t-ubuntu.zip)


and "MoskNormal" font

**Comment by OtizAdoniz** [comment]
[Mosk Normal 400.zip](https://github.com/OtizAdoniz/project-transpacific/files/829978/Mosk.Normal.400.zip)

**Comment by OtizAdoniz** [comment]
Since you are very creative and artistic, you can comeup with a title and/or logo.

**Comment by OtizAdoniz** [comment]
I am going to write a complete overview of the website i.e purpose, objectives etc. I have had a premonition that this project might actually turn out to be a success.

**Comment by OtizAdoniz** [comment]
I amde this with photoshop and it got lots of upvotes on 9gag.

**Comment by mokeira** [comment]
cool, i can start working on responsiveness once I have the page.

**Comment by OtizAdoniz** [comment]
you got the fonts, didn't you? And would you kindly suggest a working title?

**Comment by mokeira** [comment]
I have not downloaded anything but i believe the fonts looks good. Title depends on the content of the site

**Comment by OtizAdoniz** [comment]
I said that the site will be something like 9gag.

**Comment by mokeira** [comment]
yeah, i didnt think you also meant same content. ok, got it

**Comment by OtizAdoniz** [comment]
okay. I am still writing the code. Doing stuff with notepad++ can be tedious. I guess I should just use Dreamweaver.
Btw, the fonts I uploaded them in a previous comment. I won't style(css) it first.

**Comment by mokeira** [comment]
i dont think the editor you use matters...anyway, take your time :)

**Comment by OtizAdoniz** [comment]
Okay

**Comment by OtizAdoniz** [comment]
have you ever made a website? would you kindly show me it?

**Comment by mokeira** [comment]
there is a repository in my acount, CS164, it has the first website I made. I didnt upload the images, which were a major component of the whole thing,but you can scan through and see what i did, you can replace the image src/url with your own if you want to view it at work and see what it does, but it was super basic, it was my beginner class

**Comment by OtizAdoniz** [comment]
whoa! I have just seen it! It was awesome, in fact I was mind blown! In order to improve my skills, I will need to study your work.

**Comment by mokeira** [comment]
oh please, anyway, let's see what you have done so far

**Comment by OtizAdoniz** [comment]
Should I upload the html file or paste the code here?

**Comment by OtizAdoniz** [comment]
I am now creating the css file

**Comment by OtizAdoniz** [comment]
btw, Do you know I studied HTML 5 and JavaScript myself? I had a tutor for only 2 weeks and then I learned the rest through YouTube and a certain textbook. I just thought you should know

**Comment by OtizAdoniz** [comment]
I have been some research about creating a 9gag-clone website, and I have found that it can be created using PHP, unfortunately, I no 0% about PHP. I had started writing the code for our 9gag clone but it came out more like a blog. So maybe we can create a blog instead? Where you will be posting you #amateurphotography photos? I am sorry if I might have caused some inconveniences. I promise that this will be the last time.

**Comment by mokeira** [comment]
You could probably upload the files but if you want to paste the code here, you can too (although, uploading to a repo is better).

You do not need to know something to use it. If you want to use PHP and you have internet connection then there is nothing stopping you. Just Google what you want to do and there is code you can basically copy-paste and use. The whole idea of a project is to at least learn something as well as polish on what you might know. 

You would be surprised if you knew the percentage of self-taught programmers who work in the industry... their is a rumor they are at least 20% more than the people who were taught in some physical institution. That is the beauty of computer science. All you need to be a computer scientist is a computer and internet connection (actually optional). Anyway, let me stop blubbering.  

The content of the site is all up to you. You decide what you want and I help you deliver.

**Comment by OtizAdoniz** [comment]
Gee thanks for that inspiration. I have never known you to be this soft and tender-hearted. :)

**Comment by OtizAdoniz** [comment]
[Angela Photography.zip](https://github.com/OtizAdoniz/project-transpacific/files/833916/Angela.Photography.zip)

**Comment by mokeira** [comment]
You used Notepad++, is that what you said?

**Comment by OtizAdoniz** [comment]
I initially wanted to use notepad++ but went on to use Dreamweaver.

**Comment by mokeira** [comment]
lol, i could tell

**Comment by mokeira** [comment]
Ok, what's the next step?

**Comment by OtizAdoniz** [comment]
I spent so much time styling the webpage, so now you can add photos. Especially the background image and stuff. You can work on the title and logo. We need to also work on the other html files, the blog, about etc...I can create the contact page, in case someone wants to contact you directly.

**Comment by mokeira** [comment]
are you doing that now?

**Comment by mokeira** [comment]
or later

**Comment by OtizAdoniz** [comment]
Right now I want to play some Overwatch. I will continue creating in the next hour. But I am online in WhatsApp incase you need something.

**Comment by mokeira** [comment]
ok, thanks

**Pull request merged**
