### PR TITLE
Innocent's starting files

### PR DESCRIPTION
**Pull request by mokeira**
Innocent's starting webPage

### CODE REVIEW

**Comment by OtizAdoniz** [comment]
where have you reached thus fur?

**Comment by OtizAdoniz** [comment]
What editor do you use?

**Comment by mokeira** [comment]
I was making some minor UI changes, let me upload and you tell me if it looks worse. Im using notepad++

**Comment by OtizAdoniz** [comment]
That is awesome. I have just remembered that you have a large gallery of photos in your Facebook page, maybe I(you) can utilize on your blog.

**Comment by mokeira** [comment]
what plans do you have for this. is it just for practice or something you will want to use long-term? If it is long-term, then maybe you might want to think of having more content. If its just fro practice, then...

**Comment by OtizAdoniz** [comment]
It is mainly for practice, once I am good, I can be creating blogs for people. But first I want to successfully finish this one we are making.

**Comment by mokeira** [comment]
ok

**Comment by mokeira** [comment]
I added some pics

**Comment by mokeira** [comment]
The images are supposed to change when you hover, it takes a while. I dont know if its just on my side or if it's something else

**Comment by OtizAdoniz** [comment]
oooooh that is an awesome style, are you going to use JavaScript?

**Comment by mokeira** [comment]
i uploaded that part, i use minimal JS maybe thats why its not functioning very well? You can improve on that

**Comment by OtizAdoniz** [comment]
Maybe, I can try

**Comment by mokeira** [comment]
YOU: I spent so much time styling the webpage, so now you can add photos. Especially the background image and stuff. You can work on the title and logo. We need to also work on the other html files, the blog, about etc...I can create the contact page, in case someone wants to contact you directly.


I just read through this. I have added placeholder photos. Check the page and let me know if you still want a background image. I added the logo on the title bar and also, if you will have a blog, maybe have pics that reflect each entry? we can make the pics be like links. Someone clicks on the link and they are redirected to the blog or something... i dont know what you have in mind.

**Comment by OtizAdoniz** [comment]
so, where do I download it?

**Comment by mokeira** [comment]
download what

**Comment by OtizAdoniz** [comment]
you said that you had added placeholder photos...

**Comment by OtizAdoniz** [comment]
nevermind, i have seen it.

**Comment by mokeira** [comment]
cool

**Comment by OtizAdoniz** [comment]
I want to view the webpage offline, Is there a way I can do that? I am still not good with this complex GitHub interface. Is there a way like, you can edit the files and then just send me the zip, so that I can edit them offline?

**Comment by OtizAdoniz** [comment]
and kindly enlighten me on this "bootstrap" thingy.

**Comment by OtizAdoniz** [comment]
Oh, lemme go to https://www.w3schools.com/bootstrap/default.asp to check it out.

**Comment by mokeira** [comment]
Yes, you can close the repo, work on it offline then push the changes when you are done. Just google how to do this, its super easy. Use github, it's not hard enough to resort to sending zip files back and forth.

**Comment by mokeira** [comment]
In basic terms, bootstrap is a framework that has templates for nearly everything: buttons, images, forms etc etc etc. Another thing, if you want to work offline, you might have to download bootstrap files and change the image links i used because all of them refer to webPages/sites

**Comment by OtizAdoniz** [comment]
Whoa! I have seen how you have used bootstrap in the footer. It is really awesome. So, do just write the codes and those social network buttons just appear? I guess I have a lot to learn. Sensei Angela, continue enlightening me.

**Comment by OtizAdoniz** [comment]
screenshot 2

**Comment by mokeira** [comment]
what findings did you get from your research

**Comment by mokeira** [comment]
Also, are you trying to make this like a "contact me" form or you want to receive a comment when someone posts it?

**Comment by mokeira** [comment]
i see you use windows OS. is that windows 10? there is some "activate windows..." message somewhere there, so i guess its win10

**Comment by OtizAdoniz** [comment]
lol that activate windows is as a result of a malfunctioning crack that you programmers made. #pirate
It is not necessarily a "contact me".

**Comment by mokeira** [comment]
ok, what exactly do you have in mind

**Comment by OtizAdoniz** [comment]
a "comment" box. Where a user gives some data, then I as the owner of the website get the data the user gave.

**Comment by mokeira** [comment]
ok, so you want an email sent to you and the content is the comment?

**Comment by OtizAdoniz** [comment]
yeah, something like that

**Comment by mokeira** [comment]
ok, and have you done any research?

**Comment by OtizAdoniz** [comment]
Well I haven't done any research yet, Though I am planning on working on the header of the index and I want to start creating the other html files, especially "about.html"

**Comment by mokeira** [comment]
image
 You put your pic

**Comment by mokeira** [comment]
ok, got it.... good luck! let me know if you want help in anything

**Comment by OtizAdoniz** [comment]
BTW, there's a way you changed the background of index.html to #000000. I found out rather unpleasant. Would you like it if I made the margin a slightly lighter shade of black?

**Comment by mokeira** [comment]
lol, [imagine a million laugh emojis here] you can even change it to yellow! I was experimenting something

**Comment by OtizAdoniz** [comment]
Okay, I'll work on it tomorrow. You know, I will be going back to campus tomorrow so I need to prepare my stuff. But I am available in whatsapp in case you want to say goodnight or something ;-)

**Pull request merged**
