### PR TITLE
Create plans

### PR DESCRIPTION
**Pull request by mokeira**
this one

### CODE REVIEW

**Comment by OtizAdoniz** [comment]
'Create Plans'. Is that the file you have sent? I expected an .exe or .txt file

**Comment by mokeira** [comment]
it's just a file i made here, can you approve the pull request?

**Comment by OtizAdoniz** [comment]
Jesus! This interface is confusing! There are buttons everywhere. Tell me, what is this merging.

**Comment by mokeira** [comment]
> I committed some changes, see them as well. 

Basically, I have a copy of the project and when i make changes, they only happen to my copy unless i create a pull request so that you can merge the changes with the original repo.

**Pull request merged**
